version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "443:3000" # Expose port 443 (HTTPS)
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /etc/letsencrypt/live/judoquiz.com:/etc/letsencrypt/live/judoquiz.com # Mount SSL certs
