version: '3.8'

services:
  judo-quiz-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: judo-quiz-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8787
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - judo-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  judo-network:
    driver: bridge
