version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:3000" # Expose port 80 on the host and map it to port 3000 inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true
