services:
  judo-quiz-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: judo-quiz-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8787
    networks:
      - judo-network
    restart: unless-stopped

networks:
  judo-network:
    driver: bridge
